name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a64663383138dc86a9ce2fb3c9f7bf86da4770d2b3ab231bfbd0540d309eca3"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
