name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb77f16a5f7674f183c99f0fa789c5bbb3c968374c578b571489869b79fe9c2d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
