name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30f3191ec2278f8dc515e927fc39c489b73cdb70b16dc1495731b31f875a33c0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
