name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33731654e866152c6a13ccccf34a18d4353be6a1618c471ff9427bb48e8fabd9"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
