name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29a2697c31e8e08268d7fdc45fafd621f0c6371b0d246b1daac67b74549e1aad"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
