name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57f3415a217f4cbada7cb83c0f58c2fdc7fee2fa98b7fec6455966fd718917d5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
