name = "Packwiz Fabric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa8ab0311ab49b4c4865b13337993992d7bb4564b7f51dae31c00adb89ffd89d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
