name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "037b21ec64b45120dc8ccfe5d471a49b3308a801db1a7ef2a3232d21c880190e"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
