name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29314bbec93724138865f1373516403e2dcdad4e664443e0f954e70b4fefaef4"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
