name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a0f7315047b7f02a254d68e8092feded5601303c55bd6c75834166d1c0db6d5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
