name = "Packwiz Fabric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "024806b3b609767c414bea8463fda54d8e08b196485fee0c74667b0c282ffbef"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
