name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86bdcbc7432dc1f26d22921de7af55287809c023b803ba410f354491bc727de3"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
