name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62e86b5a99aec2ae9185d98b8a0815ae50b04fa5a87a72f94c709e9f735676bc"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
