name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30ba6e438fc4acd3e9082096cc2db2858fe80cfb6b05e50484d2afe0439e6f79"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
