name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0210ab59d59dc6cb03facb5e020f199d88868199eb51825fc15802d83436fe2"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
