name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14d81197cbaebe52ebdf3ea1b0a9b62bdbe297a05f769abf329d9979b05ac311"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
