name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "606c9504da0c6a288d0027bff2bfbe4d3519029546acf0b2b8689129b4ecac68"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
