name = "Packwiz TEST"
author = "MrMoBlazing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2307ef86504c82ab0cfb4c16a4ec218e6941a43c4e976f9f6609a33e920a29b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
