name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7d5f692fcc1acddef42276ea48dcfeb643113ec2229a89621e9bfe2e58e37db"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
