name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e083e27255a85ea2454a874b8c14f9b9ade4d6575a7e274a71ce844b602bce58"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
