name = "Packwiz Fabric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "796a251deb2f71283dab79f06cf6117b2607eb38bbaa373512372fd665c1078e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
