name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "940aacc1ddf40b30474d52a15467f9c929c1f3eafe55ac2c25cf9a860ea8db17"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
