name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c2177d076119d56132f7ba63ec908171afe13db25b49e594b7ba1a558e0c184"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
