name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c30423fa545b135be39cfd7b0f3f40e6b8fe6b839582ff85df5382bf1a4fcf0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
