name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f415b2984cfe9a1d0f76f4c06bae096b703f662c0b262da8a4324a12403ce53"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
