name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fa56f6ee7a6ffdfb39bb25bee300ee7e788f8c961d1f6edc138bc8359b849ad"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
