name = "Packwiz Fabric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4699de61503da342d77c1df8801a292abe7f9d3cf81e7c8b2b3e295813fca344"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
