name = "Packwiz TEST"
author = "MrMoBlazing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1641b5dd18a855c99d2d9421977ccc680ccc939928b1f986560ebf196d016836"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
