name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "808c3da8f2603b0357f826ab76ad8ce1985ad859a4cd2a00053bcb2a4b1767ef"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
