name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a87ea71d43d9a66f58b3da7922c88ff815cbb6cec9da8c34e7d76a50179e29b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
