name = "Morganism"
author = "Mo9713"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6656761ce6202b68597bebc078c38c019b2fbbfb0c56dd09cced6678d02facf8"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
