name = "Packwiz Fabric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e8da4279d5ade20a7e03896dd5e01975a9e3252aacb81e2217e7a4137ce2ab"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
