name = "Architectury API (Fabric)"
filename = "architectury-3.7.38.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3728/612/architectury-3.7.38.jar"
hash-format = "murmur2"
hash = "2147342348"

[update]
[update.curseforge]
file-id = 3728612
project-id = 419697
