name = "Architectury API (Fabric)"
filename = "architectury-3.7.19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/921/architectury-3.7.19.jar"
hash-format = "murmur2"
hash = "2252692641"

[update]
[update.curseforge]
file-id = 3651921
project-id = 419697
