name = "BCLib"
filename = "bclib-1.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/694/bclib-1.3.3.jar"
hash-format = "murmur2"
hash = "3922750685"

[update]
[update.curseforge]
file-id = 3649694
project-id = 495191
