name = "BCLib"
filename = "bclib-1.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/592/bclib-1.3.5.jar"
hash-format = "murmur2"
hash = "155755494"

[update]
[update.curseforge]
file-id = 3680592
project-id = 495191
