name = "BCLib"
filename = "bclib-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/933/bclib-1.3.2.jar"
hash-format = "murmur2"
hash = "4061648963"

[update]
[update.curseforge]
file-id = 3648933
project-id = 495191
