name = "BetterCombatExperience"
filename = "bce-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/700/bce-1.0.0.jar"
hash-format = "murmur2"
hash = "324114315"

[update]
[update.curseforge]
file-id = 3629700
project-id = 574564
