name = "Clickable advancements[Forge/Fabric]"
filename = "clickadv-fabric-2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3658/897/clickadv-fabric-2.4.jar"
hash-format = "murmur2"
hash = "1833414077"

[update]
[update.curseforge]
file-id = 3658897
project-id = 511733
