name = "Essential Commands"
filename = "essential_commands-0.20.2-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3656/845/essential_commands-0.20.2-mc1.18.1.jar"
hash-format = "murmur2"
hash = "2794582533"

[update]
[update.curseforge]
file-id = 3656845
project-id = 475964
