name = "Essential Commands"
filename = "essential_commands-0.19.0-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3574/394/essential_commands-0.19.0-mc1.18.1.jar"
hash-format = "murmur2"
hash = "1494074699"

[update]
[update.curseforge]
file-id = 3574394
project-id = 475964
