name = "Essential Commands"
filename = "essential_commands-0.20.0-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/202/essential_commands-0.20.0-mc1.18.1.jar"
hash-format = "murmur2"
hash = "3585868138"

[update]
[update.curseforge]
file-id = 3639202
project-id = 475964
