name = "Essential Commands"
filename = "essential_commands-0.20.4-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/433/essential_commands-0.20.4-mc1.18.1.jar"
hash-format = "murmur2"
hash = "3801638683"

[update]
[update.curseforge]
file-id = 3683433
project-id = 475964
