name = "Extra Origins"
filename = "extraorigins-1.18-9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/247/extraorigins-1.18-9.jar"
hash-format = "murmur2"
hash = "4207862658"

[update]
[update.curseforge]
file-id = 3646247
project-id = 398419
