name = "Fabric API"
filename = "fabric-api-0.72.0+1.19.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "d89a3e956e4e42fd4c14f85975df948ab7a519eb"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4302481
project-id = 306612
