name = "Health Overlay (Fabric)"
filename = "HealthOverlay-1.18.1-6.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3563/686/HealthOverlay-1.18.1-6.0.1.jar"
hash-format = "murmur2"
hash = "1649209553"

[update]
[update.curseforge]
file-id = 3563686
project-id = 313219
