name = "Lato Origins"
filename = "LatoOrigins-1.18.1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/124/LatoOrigins-1.18.1-1.0.0.jar"
hash-format = "murmur2"
hash = "3188238568"

[update]
[update.curseforge]
file-id = 3639124
project-id = 463325
