name = "Medieval Origins"
filename = "medieval-origins-1.18.x-3.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3692/414/medieval-origins-1.18.x-3.3.2.jar"
hash-format = "murmur2"
hash = "1948934305"

[update]
[update.curseforge]
file-id = 3692414
project-id = 508051
