name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.2.412.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/828/RoughlyEnoughItems-7.2.412.jar"
hash-format = "murmur2"
hash = "1785198889"

[update]
[update.curseforge]
file-id = 3627828
project-id = 310111
