name = "Roughly Searchable"
filename = "roughly-searchable-2.3.0+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/830/roughly-searchable-2.3.0+1.18.1.jar"
hash-format = "murmur2"
hash = "3809953429"

[update]
[update.curseforge]
file-id = 3575830
project-id = 392023
