name = "TerraBlender (Fabric)"
filename = "TerraBlender-fabric-1.18.1-1.1.0.75.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/536/TerraBlender-fabric-1.18.1-1.1.0.75.jar"
hash-format = "murmur2"
hash = "126048903"

[update]
[update.curseforge]
file-id = 3648536
project-id = 565956
