name = "Thymine"
filename = "thymine-1.7.2-mc1.18.jar"
side = "both"

[download]
url = "https://github.com/Toshimichi0915/Thymine/releases/download/v1.7.2/thymine-1.7.2-mc1.18.jar"

# A number of tools can generate the hash for you, including 7-zip and sha256sum
# packwiz supports a number of hashes, including sha256, sha512, sha1 and md5
hash-format = "sha256"
hash = "7a688ed0708f1934bde4b4296c6e03a220adb941fd2885d32bb05190e0e6708d"