name = "TooManyOrigins"
filename = "TooManyOrigins-1.18-0.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3687/843/TooManyOrigins-1.18-0.4.2.jar"
hash-format = "murmur2"
hash = "1990009578"

[update]
[update.curseforge]
file-id = 3687843
project-id = 469658
