name = "TooManyOrigins"
filename = "TooManyOrigins-1.18-0.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/884/TooManyOrigins-1.18-0.4.1.jar"
hash-format = "murmur2"
hash = "1987750175"

[update]
[update.curseforge]
file-id = 3652884
project-id = 469658
