name = "Twigs"
filename = "twigs-1.1.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3597/733/twigs-1.1.3-fabric.jar"
hash-format = "murmur2"
hash = "1538248487"

[update]
[update.curseforge]
file-id = 3597733
project-id = 496913
