name = "WTHIT"
filename = "wthit-fabric-4.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/26/wthit-fabric-4.5.3.jar"
hash-format = "murmur2"
hash = "2128223550"

[update]
[update.curseforge]
file-id = 3662026
project-id = 440979
