name = "WTHIT"
filename = "wthit-fabric-4.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3634/609/wthit-fabric-4.5.0.jar"
hash-format = "murmur2"
hash = "116277680"

[update]
[update.curseforge]
file-id = 3634609
project-id = 440979
