name = "YUNG's API (Fabric)"
filename = "YungsApi-1.18-Fabric-35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/252/YungsApi-1.18-Fabric-35.jar"
hash-format = "murmur2"
hash = "203927905"

[update]
[update.curseforge]
file-id = 3631252
project-id = 421649
